### PR TITLE
🐛 fix(front,back): Fix the side panel opening

### LINKED ISSUE #43: Side panel does not open when navigating to a LinkedIn profile from another LinkedIn page
See the video below ⤵️

https://www.loom.com/share/465f2a30c0a2407eb56684ae5bd849ce?sid=b75a2e5f-19b9-46a3-a239-c9343cf201ff

### PR DESCRIPTION
**Pull request by GauvainThery**
# Context

See the issue.

# Solution

https://www.loom.com/share/9f981662c3304f108dcc22e1701a803b?sid=a4ab184d-ce65-4c00-9871-af610f1c33da

# Priority

High

### CODE REVIEW

File: apps/linkedin-to-notion/src/background/index.ts [hunk 1]
```diff
@@ -4,16 +4,17 @@ export {};
 
 // You can test the regex here: https://regex101.com/r/RJgYar/1
 // Don't forget to update the comment when you update the regex on regex101.com
-export const linkedInURLRegex = /linkedin\.com\/in\/[^/]+\/#?$/;
+export const linkedInURLRegex = /linkedin\.com\/in\/[^/]+\/#?/;
```
Comment (GauvainThery) [inline apps/linkedin-to-notion/src/background/index.ts:7]: This is needed because when LinkedIn changes url, it starts with a weird url like `https://www.linkedin.com/in/nije-üô/?mini_profile...` so it closes the panel that we want to keep open when switching from one profile to another

File: apps/linkedin-to-notion/src/contents/linkedin-notion-side-panel.tsx [hunk 2]
```diff
@@ -11,7 +11,7 @@ import { supabase } from '~core/supabase';
 import { LinkedInNotionSidePanelContent } from '../components/LinkedInNotionSidePanel/LinkedInNotionSidePanelContent';
 
 export const config: PlasmoCSConfig = {
-  matches: ['https://www.linkedin.com/in/*'],
+  matches: ['https://www.linkedin.com/*'],
```
Comment (GauvainThery) [inline apps/linkedin-to-notion/src/contents/linkedin-notion-side-panel.tsx:14]: LinkedIn is kind of a single page application so there's no real page changes. If we don't match on this URL we have to reload the page when we're on a profile to inject the CS

File: apps/linkedin-to-notion/src/contents/linkedin-notion-side-panel.tsx [hunk 3]
```diff
@@ -23,7 +23,7 @@ export const getStyle: PlasmoGetStyle = () => {
 };
 
 const LinkedinNotionSidePanel = () => {
-  const [isOpen, setIsOpen] = useState(true); // set-back to false before deployment
+  const [isOpen, setIsOpen] = useState(false);
```
Comment (GauvainThery) [inline apps/linkedin-to-notion/src/contents/linkedin-notion-side-panel.tsx:26]: Close to the release and was needed to test ;)

**Comment by bvelitchkine** [comment]
LGTM!

**Review by bvelitchkine — APPROVED** [review]
LGTM!
